[program:kgparl-api]
command=/opt/docker/fp/api/kgparl-api
directory=/opt/docker/fp/api
environment=PROJECT_ROOT="/opt/docker/fp"
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/var/log/kgparl-api.log
stderr_logfile=/var/log/kgparl-api-error.log
user=stephan
