#!/usr/bin/env python3
"""
Generate JavaScript configuration file from environment settings.

Usage:
    python generate_js_config.py --env live
    python generate_js_config.py --env test
"""

import argparse
import json
import os
from pathlib import Path
from dotenv import load_dotenv

# Get the project root directory
PROJECT_ROOT = Path(__file__).parent.parent
CONFIG_DIR = PROJECT_ROOT / "config"
OUTPUT_FILE = PROJECT_ROOT / "html" / "js" / "config.js"


def load_environment_config(env_name: str) -> dict:
    """Load configuration from environments.json for the specified environment."""
    env_file = CONFIG_DIR / "environments.json"

    if not env_file.exists():
        raise FileNotFoundError(f"Environment config file not found: {env_file}")

    with open(env_file, "r", encoding="utf-8") as f:
        all_configs = json.load(f)

    if env_name not in all_configs:
        raise ValueError(f"Unknown environment: {env_name}. Available: {list(all_configs.keys())}")

    return all_configs[env_name]


def load_env_file(env_name: str) -> dict:
    """Load all settings from the environment-specific .env file."""
    env_file = CONFIG_DIR / f"{env_name}.env"

    if not env_file.exists():
        raise FileNotFoundError(f"Environment secrets file not found: {env_file}")

    # Load the environment file
    load_dotenv(env_file, override=True)

    return {
        "apiKey": os.getenv("TYPESENSE_API_KEY", ""),
        "adminKey": os.getenv("TYPESENSE_ADMIN_KEY", ""),
        "githubToken": os.getenv("GITHUB_TOKEN", ""),
        "host": os.getenv("TYPESENSE_HOST", ""),
        "port": os.getenv("TYPESENSE_PORT", ""),
        "protocol": os.getenv("TYPESENSE_PROTOCOL", ""),
        "timeout": os.getenv("TYPESENSE_TIMEOUT", ""),
    }


def generate_js_config(env_name: str) -> str:
    """Generate the JavaScript configuration content."""
    config = load_environment_config(env_name)
    env = load_env_file(env_name)

    collections = config["typesense"]["collections"]

    # Connection settings from .env, fallback to environments.json
    ts_json = config["typesense"]
    host = env["host"] or ts_json["host"]
    port = env["port"] or str(ts_json["port"])
    protocol = env["protocol"] or ts_json["protocol"]
    timeout = env["timeout"] or str(ts_json["timeout"])

    js_content = f'''// Auto-generated configuration file
// Environment: {env_name}
// DO NOT EDIT MANUALLY - Generated by scripts/generate_js_config.py

const TYPESENSE_CONFIG = {{
  host: "{host}",
  port: {port},
  protocol: "{protocol}",
  timeout: {timeout},
  apiKey: "{env['apiKey']}",
}};

const TYPESENSE_COLLECTIONS = {{
  protocols: "{collections['protocols']}",
  persons: "{collections['persons']}",
  literature: "{collections['literature']}",
  einleitung: "{collections['einleitung']}",
  keywords: "{collections['keywords']}",
}};

// Current environment
const CURRENT_ENV = "{env_name}";

// Export for ES modules (if used)
if (typeof module !== 'undefined' && module.exports) {{
  module.exports = {{ TYPESENSE_CONFIG, TYPESENSE_COLLECTIONS, CURRENT_ENV }};
}}
'''
    return js_content


def main():
    parser = argparse.ArgumentParser(
        description="Generate JavaScript configuration from environment settings"
    )
    parser.add_argument(
        "--env",
        choices=["live", "test"],
        default="live",
        help="Environment to generate config for (default: live)"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=f"Output file path (default: {OUTPUT_FILE})"
    )

    args = parser.parse_args()
    output_file = args.output or OUTPUT_FILE

    print(f"Generating JavaScript config for environment: {args.env}")

    try:
        js_content = generate_js_config(args.env)

        # Ensure output directory exists
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(js_content)

        print(f"Configuration written to: {output_file}")

    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
